### ISSUE TITLE
Error in MeasureTool.py

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-MeasureTool#4]
**from .MeasureToolHandle import MeasureToolHandle**   
No MeasureToolHandle   existing ( for the moment ? )

**Comment by deftdawg** [comment]
I get same on both Cura 4.7.1 and Cura 4.8.0 on Windows 10 (running `curacli.exe --debug`): 
```
2021-01-24 17:04:36,423 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin MachineSettingsAction
2021-01-24 17:04:36,443 - ERROR - [MainThread] UM.Logger.logException [106]: Exception: Import error loading module MeasureTool
2021-01-24 17:04:36,460 - ERROR - [MainThread] UM.Logger.logException [110]: Traceback (most recent call last):
2021-01-24 17:04:36,464 - ERROR - [MainThread] UM.Logger.logException [110]:   File "X:\4.8-exe\build\inst\lib\python3.5\site-packages\UM\PluginRegistry.py", line 667, in _findPlugin
2021-01-24 17:04:36,468 - ERROR - [MainThread] UM.Logger.logException [110]:   File "imp.py", line 245, in load_module
2021-01-24 17:04:36,472 - ERROR - [MainThread] UM.Logger.logException [110]:   File "imp.py", line 217, in load_package
2021-01-24 17:04:36,476 - ERROR - [MainThread] UM.Logger.logException [110]:   File "<frozen importlib._bootstrap>", line 693, in _load
2021-01-24 17:04:36,480 - ERROR - [MainThread] UM.Logger.logException [110]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2021-01-24 17:04:36,485 - ERROR - [MainThread] UM.Logger.logException [110]:   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
2021-01-24 17:04:36,489 - ERROR - [MainThread] UM.Logger.logException [110]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2021-01-24 17:04:36,495 - ERROR - [MainThread] UM.Logger.logException [110]:   File "C:\Program Files\Ultimaker Cura 4.8.0\plugins\MeasureTool\__init__.py", line 4, in <module>
2021-01-24 17:04:36,499 - ERROR - [MainThread] UM.Logger.logException [110]:     from . import MeasureTool
2021-01-24 17:04:36,506 - ERROR - [MainThread] UM.Logger.logException [110]:   File "C:\Program Files\Ultimaker Cura 4.8.0\plugins\MeasureTool\MeasureTool.py", line 13, in <module>
2021-01-24 17:04:36,511 - ERROR - [MainThread] UM.Logger.logException [110]:     from .MeasureToolHandle import MeasureToolHandle
2021-01-24 17:04:36,516 - ERROR - [MainThread] UM.Logger.logException [110]: ImportError: No module named 'MeasureTool.MeasureToolHandle'
2021-01-24 17:04:36,524 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [739]: Could not find plugin MeasureTool
2021-01-24 17:04:36,531 - ERROR - [MainThread] UM.Logger.logException [106]: Exception: Import error loading module MeasureTool
2021-01-24 17:04:36,536 - ERROR - [MainThread] UM.Logger.logException [110]: Traceback (most recent call last):
2021-01-24 17:04:36,542 - ERROR - [MainThread] UM.Logger.logException [110]:   File "X:\4.8-exe\build\inst\lib\python3.5\site-packages\UM\PluginRegistry.py", line 667, in _findPlugin
2021-01-24 17:04:36,546 - ERROR - [MainThread] UM.Logger.logException [110]:   File "imp.py", line 245, in load_module
2021-01-24 17:04:36,551 - ERROR - [MainThread] UM.Logger.logException [110]:   File "imp.py", line 217, in load_package
2021-01-24 17:04:36,557 - ERROR - [MainThread] UM.Logger.logException [110]:   File "<frozen importlib._bootstrap>", line 693, in _load
2021-01-24 17:04:36,561 - ERROR - [MainThread] UM.Logger.logException [110]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2021-01-24 17:04:36,566 - ERROR - [MainThread] UM.Logger.logException [110]:   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
2021-01-24 17:04:36,572 - ERROR - [MainThread] UM.Logger.logException [110]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2021-01-24 17:04:36,576 - ERROR - [MainThread] UM.Logger.logException [110]:   File "C:\Program Files\Ultimaker Cura 4.8.0\plugins\MeasureTool\__init__.py", line 4, in <module>
2021-01-24 17:04:36,582 - ERROR - [MainThread] UM.Logger.logException [110]:     from . import MeasureTool
2021-01-24 17:04:36,586 - ERROR - [MainThread] UM.Logger.logException [110]:   File "C:\Program Files\Ultimaker Cura 4.8.0\plugins\MeasureTool\MeasureTool.py", line 13, in <module>
2021-01-24 17:04:36,592 - ERROR - [MainThread] UM.Logger.logException [110]:     from .MeasureToolHandle import MeasureToolHandle
2021-01-24 17:04:36,600 - ERROR - [MainThread] UM.Logger.logException [110]: ImportError: No module named 'MeasureTool.MeasureToolHandle'
2021-01-24 17:04:36,615 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin ModelChecker
```

@fieldOfView I know you've said you don't believe this plugin is marketplace worthy, but can I can convince you to reconsider?  In the absense of anything else, having this available (even if it was labeled Alpha / dev help wanted) would be very helpful.  thx

**Comment by deftdawg** [comment]
@5axes I think perhaps there are some changes happening this plugin that weren't fully committed.

You can temporarily bypass the issue with missing MeasureToolHandle import by commenting out line 13 of plugin, however for me it crashes cura when I attempt to use it.
 
```diff
diff --git a/MeasureTool.py b/MeasureTool.py
index 4d721f6..36e09ad 100644
--- a/MeasureTool.py
+++ b/MeasureTool.py
@@ -10,7 +10,7 @@ from UM.i18n import i18nCatalog
 from cura.CuraApplication import CuraApplication
 from cura.Scene.CuraSceneNode import CuraSceneNode
 from .MeasurePass import MeasurePass
-from .MeasureToolHandle import MeasureToolHandle
+# from .MeasureToolHandle import MeasureToolHandle

 from PyQt5.QtCore import QObject
 from PyQt5.QtGui import QVector3D
```

**Comment by fieldOfView** [comment]
Like I have said before, this plugin is not ready for prime-time. I do not recommend using it.

Having said that, I unintentionally included the aforementioned import in an unrelated commit. I have now added the missing class, though it is only a stub; it adds no functionality yet.
